# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jQ0rdD5EJo7qtwpWyOM6QV7LAMN-ebJ_
"""

my_list = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
my_list[::2]

n = [23, 'Python', 23.98]
m=n
print(m)
print(type(n[0]),type(n[1]),type(n[2]))

def pattern(n):
    
    for i in range (1, n+1):
        for j in range (1, i+1):
            print (" *",end=" ")
        print()
     
    for i in range (n, 1, -1):
            for j in range (i, 1, -1):
                print (" *",end=" ")
            print()    
pattern(5)

b='The quick Brow Fox'
a=sum(1 for c in b if c.isupper())
print("No. of Upper-case characters:",a)
c=sum(1 for c in b if c.islower())
print("No. of Lower-case Characters:",c)

d = [1,2,3,3,3,3,4,5]
output = []
for x in d:
    if x not in output:
        output.append(x)
print(output)